print("-------------------Area of Circle-------------------")
radius = int(input("Enter radius of circle          :"))
area = 3.14 * (radius*radius)
print("Area of circle is        :" ,area)
print("-------------------Area of Rectangle-------------------")
length = int(input("Enter Length of Rectangle       :"))
breadth = int(input("Enter Breadth of Recatngle      :"))
area = length * breadth
print("Area of Reactangle is    :" ,area)
print("-------------------Area of Triangle-------------------")
Height = float(input("Enter Height of Triangle        :"))
Base = float(input("Enter Base of Triangle          :"))
area = float(1/2*Height*Base)
print("Area of Triangle is      :" ,area)